# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b7bd31a19331e4736575bfa88e2f73d13b31c9de7a83591d2ae858171c5f1265e77b2dbb514a523c802bf3be998f85288134efe653991e2e2e58601a808eb6d

test:
  secret_key_base: 1fc5e7fde46017f10014c955211708a7da2b90a5070cc9c658ec7cbd1f8c36e5db1eb05c9479fc37faf0c1bd7a9845932bfe5b7614e647664546a381db25ab5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
